export const surpriseMePrompts = [
  'A cozy cottage made entirely of books, nestled in a mystical forest, watercolor',
  'A robot chef preparing sushi in a futuristic kitchen, digital art',
  'A majestic lion wearing a crown of flowers, surrounded by butterflies, digital painting',
  'A whimsical cityscape where buildings are made of candy, with chocolate rivers and gingerbread houses',
  'A giant octopus serving coffee in a hipster cafe, 3D render',
  'A futuristic city floating above the clouds, connected by glass bridges, digital art',
  'A playful squirrel wearing aviator goggles, piloting a tiny red biplane, 50mm photography',
  'A serene underwater library with glowing books and jellyfish floating around, digital art',
  'A snail with a tiny mushroom as a shell, exploring a miniature fairy garden, macro photography',
  'A medieval knight in shining armor, riding a unicorn through a bustling modern city, digital art',
  'A steampunk owl with mechanical wings perched on a vintage clock, concept art',
  'A panda astronaut planting a bamboo flag on the moon, digital painting',
  'A raccoon DJ spinning records at an outdoor forest party, festival lights and fireworks in the background',
  'A watercolor painting of a futuristic garden with plants glowing in neon colors, sci-fi theme',
  'A Victorian-era family portrait of cats wearing formal attire, vintage photography',
  'A magical tree with branches that grow lanterns instead of leaves, glowing in the twilight, digital art',
  'A surreal desert landscape with floating cacti and pink sand dunes, dreamlike painting',
  'A pug dressed as a pirate, steering a ship through stormy seas, comic book style',
  'A serene tea ceremony taking place on a floating rock in the sky, surrounded by clouds, fantasy art',
  'A clockwork dragon guarding a treasure chest of gears and golden cogs, steampunk illustration',
  'A fox wearing a wizard hat and cape, reading a spellbook in a candle-lit library, illustration',
  'A penguin wearing a tuxedo, posing on a red carpet with paparazzi flashing cameras, digital art',
  'A vintage polaroid of a UFO sighting over a sunflower field at sunset',
  'A close-up photograph of a tiny frog playing a miniature grand piano in the jungle',
  'A dolphin jumping through a glowing neon ring in a futuristic aquarium, synthwave art',
  'A magical mushroom forest with bioluminescent fungi illuminating the path, fantasy digital art',
  'An ancient Greek statue of Zeus wearing modern sunglasses and holding a smartphone',
  'A detective penguin with a magnifying glass, searching for clues in a snowy landscape, film noir style',
  'A digital painting of a cyberpunk fox wearing a hoodie and neon glasses',
  'A hot air balloon shaped like a giant teapot, floating over a quaint village, illustration',
  'A portrait of a wise old turtle with a long beard and round glasses, digital painting',
  'A neon sign that reads "Time Travel Agency" hanging on a rainy street in Tokyo, cyberpunk photography',
  'A retro-futuristic diner where robots are serving milkshakes and burgers',
  'A polar bear wearing sunglasses and riding a jet ski, digital art',
  'A mystical underwater palace made of coral and pearls, illuminated by fish carrying lanterns',
  'A jungle scene with animals gathered around a laptop, watching a movie together, digital art',
  'A futuristic library where holographic books float around, sci-fi digital art',
  'A llama wearing a superhero cape, flying through the clouds, comic book style',
  'A realistic photograph of a chameleon camouflaged to look like a rainbow gradient',
  'A cybernetic deer wandering through a neon-lit forest, glowing antlers, digital art',
  'A bakery in Paris where pastries are shaped like adorable animals, kawaii style',
  'A fantasy scene of a wizard owl casting a spell in a moonlit forest',
  'A spaceship designed like a giant seashell, flying through the stars, fantasy art',
  'A portrait of an octopus wearing a monocle and a top hat, Victorian illustration',
  'A dragon reading a book in a cozy library with a fireplace, digital painting',
  'An astronaut holding a bouquet of glowing alien flowers on a distant planet, surreal art',
  'A snail with a house-like shell, complete with windows and a tiny chimney, digital illustration',
  'A time-traveling cat with goggles, exploring ancient Egypt, steampunk style',
];